### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by mashtonian** [vyachkonovalov/polybar-gmail#41]
About a week ago this stopped working for me and throws the error below when executed:

Traceback (most recent call last):
  File "/usr/bin/bar-gmail", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/bar_gmail/__init__.py", line 75, in cli
    app.run()
  File "/usr/lib/python3.12/site-packages/bar_gmail/app.py", line 84, in run
    session = json.loads(f.read())
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by crabvk** [comment]
Try to remove cache at ~/.cache/bar-gmail (all files) and run `bar-gmail` again.

**Comment by mashtonian** [comment]
aha, yes that worked. Thank you!
