### ISSUE TITLE
getting error after updating python-google-api-python-client to 1.8.0-1

### ISSUE THREAD

**Issue by ashish-yadav11** [vyachkonovalov/polybar-gmail#9]
I get the following errors when running launch.py after the update -

`Traceback (most recent call last):
  File "/home/ashish/.config/polybar/scripts/gmail/launch.py", line 7, in <module>
    from apiclient import discovery, errors
  File "/usr/lib/python3.8/site-packages/apiclient/__init__.py", line 8, in <module>
    from googleapiclient import discovery
  File "/usr/lib/python3.8/site-packages/googleapiclient/discovery.py", line 49, in <module>
    import google.api_core.client_options`

I use arch linux and i installed python-google-api-python-client and python-oauth2client packages from its official repository.

**Comment by crabvk** [comment]
Made the update, note new deps.
